//-----------------------------------------------------------------------
// <copyright file="ReturnCloneActionTest.cs" company="NMock2">
//
//   http://www.sourceforge.net/projects/NMock2
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
// This is the easiest way to ignore StyleCop rules on this file, even if we shouldn't use this tag:
// <auto-generated />
//-----------------------------------------------------------------------
namespace NMock2.Test.Actions
{
    using System;
    using NMock2.Actions;
    using NUnit.Framework;

    [TestFixture]
    public class ReturnCloneActionTest
    {
        [Test]
        public void ReturnsCloneOfPrototypeObject()
        {
            ICloneable prototype = ACloneableObject();
            IAction action = new ReturnCloneAction(prototype);
            
            object result = ReturnActionTest.ResultOfAction(action);
            Verify.That(result, !Is.Same(prototype));
        }
        
        [Test]
        public void HasAReadableDescription()
        {
            ICloneable prototype = ACloneableObject();
            AssertDescription.IsEqual(new ReturnCloneAction(prototype),
                                      "a clone of <"+prototype+">");
        }

        #region Unimportant test definitions
        private ICloneable ACloneableObject()
        {
            return new NamedObject("a cloneable object");
        }
        #endregion
    }
}

