//-----------------------------------------------------------------------
// <copyright file="UsingBlockAcceptanceTest.cs" company="NMock2">
//
//   http://www.sourceforge.net/projects/NMock2
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
// This is the easiest way to ignore StyleCop rules on this file, even if we shouldn't use this tag:
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using NUnit.Framework;

namespace NMocha.AcceptanceTests {
    [TestFixture]
    public class UsingBlockAcceptanceTest : AcceptanceTestBase {
        public interface IUsingBlock {
            int IntReturnValue();
            void NoReturnValue();
        }

        [TestFixtureSetUp]
        public void TestFixtureSetUp() {
            SkipVerificationForThisFixture();
        }


        
        [Test, ExpectedException(typeof (InvalidOperationException))]
        public void ReturnValueForgottenWithVerify() {
            var usingBlock = Mockery.NewInstanceOfRole<IUsingBlock>();

            Expect.Once.On(usingBlock).Message("IntReturnValue"); // Developer forgot to set: .Will(Return.Value(12));
            Expect.Once.On(usingBlock).Message("NoReturnValue");
            usingBlock.IntReturnValue();
            usingBlock.NoReturnValue();
        }
    }
}