//-----------------------------------------------------------------------
// <copyright file="StringContainsMatcherTest.cs" company="NMock2">
//
//   http://www.sourceforge.net/projects/NMock2
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
// This is the easiest way to ignore StyleCop rules on this file, even if we shouldn't use this tag:
// <auto-generated />
//-----------------------------------------------------------------------
using NMocha;
using NMock2.Matchers;
using NUnit.Framework;

namespace NMock2.Test.Matchers {
    [TestFixture]
    public class StringContainsMatcherTest {
        [Test]
        public void HasAReadableDescription() {
            string substring = "substring";
            AssertDescription.IsEqual(new StringContainsMatcher(substring),
                                      "containing \"" + substring + "\"");
        }

        [Test]
        public void MatchesIfStringArgumentContainsGivenSubstring() {
            string substring = "SUBSTRING";
            Matcher matcher = new StringContainsMatcher(substring);

            Assert.IsTrue(matcher.Matches(substring), "arg is substring");
            Assert.IsTrue(matcher.Matches(substring + "X"), "arg starts with substring");
            Assert.IsTrue(matcher.Matches("X" + substring), "arg ends with substring");
            Assert.IsTrue(matcher.Matches("X" + substring + "X"), "arg contains substring");
            Assert.IsFalse(matcher.Matches("XX"), "arg does not contain substring");
            Assert.IsFalse(matcher.Matches(null), "arg is null");
            Assert.IsFalse(matcher.Matches(new object()), "arg is not a string");
        }
    }
}