//-----------------------------------------------------------------------
// <copyright file="NamedObject.cs" company="NMock2">
//
//   http://www.sourceforge.net/projects/NMock2
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
// This is the easiest way to ignore StyleCop rules on this file, even if we shouldn't use this tag:
// <auto-generated />
//-----------------------------------------------------------------------
namespace NMock2.Test
{
    using System;

    public class NamedObject : ICloneable
    {
        private readonly string id;
        private readonly int cloneId;
        
        public NamedObject(string id) : this(id, 0)
        {
        }
        
        public NamedObject(string id, int cloneId)
        {
            this.id = id;
            this.cloneId = cloneId;
        }
        
        public override string ToString()
        {
            return id + (cloneId > 0 ? " (clone " + cloneId + ")" : "");
        }
        
        public object Clone()
        {
            return new NamedObject(id, cloneId+1);
        }
    }
}
