//-----------------------------------------------------------------------
// <copyright file="OutParamAcceptanceTest.cs" company="NMock2">
//
//   http://www.sourceforge.net/projects/NMock2
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
// This is the easiest way to ignore StyleCop rules on this file, even if we shouldn't use this tag:
// <auto-generated />
//-----------------------------------------------------------------------
using NMock2.Monitoring;
using NUnit.Framework;

namespace NMock2.AcceptanceTests {
    [SetUpFixture]
    public class SetupFixture {
        [SetUp]
        public void BeforeAnyTestsAreRun() {
            SetMockObjectFactoryToDefault();
        }

        /// <summary>
        /// Changes the default IMockObjectFactory for all subsequently created
        /// Mockery instances. On occasion, this method may need to be called directly
        /// from a test fixture if testing the ability to swap factory implementations.
        /// </summary>
        public static void SetMockObjectFactoryToDefault() {
            // The legacy InterfaceOnlyMockObjectFactory implementation can be tested
            // by setting this compiler define and running only the tests in the
            // 'Interface' NUnit category.
#if INTERFACEONLY
            Mockery.ChangeDefaultMockObjectFactory(typeof(InterfaceOnlyMockObjectFactory));
#else
            Mockery.ChangeDefaultMockObjectFactory(typeof (CastleMockObjectFactory));
#endif
        }
    }
}